### ISSUE TITLE
Maquette du site

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/etat#2]
Proposition de maquette par @NDOY3M4N #1 

# Proposition 1
![wire1-home](https://user-images.githubusercontent.com/84446/111630500-54d0d000-87ea-11eb-929b-6bbb9390d122.png)

# Proposition 2
![wire2-home](https://user-images.githubusercontent.com/84446/111630525-5c907480-87ea-11eb-9dfe-d15d05c505f0.png)

**Comment by dofbi** [comment]
Hello @NDOY3M4N 
Tu viens d'être ajouter [au tableau des décorations](https://github.com/Code-for-Senegal/Diambars-Decorations) des contributeurs ta classe de mérite **chevalier**🎖️avec une contribution barvo 👏🏾 👏🏾 👏🏾 

Pour les mode classic ou Dark fait selon ton felling et ta priorité à nous de nous d'adapter, se pense que tu peux intégrer les couleur national dans ton travail 🇸🇳

**Comment by NDOY3M4N** [comment]
Harigato for the medal 🙏🏿.
Je vais continuer de travailler sur le design et essayer d'y ajouter les couleurs nationales

**Comment by dofbi** [comment]
Hello @NDOY3M4N 
Je viens de voir le travail cool
Serait-il possible de prévoir un thumb pour les captures d'écran des sites.
Merci

**Comment by dofbi** [comment]
Voici mon avis

> Hello @NDOY3M4N
> Je viens de voir le travail cool
> Serait-il possible de prévoir un thumb pour les captures d'écran des sites.
> Merci

Tu peux déjà consulter le travail d'intégration ici
https://etat.codeforsenegal.org
